title:              The Undefined Void
email:              rafaelmalgor@gmail.com
description:        An uncaught exception
author:             Rafael Malgor
baseurl:            "/blog"
url:                "https://rafaelmalgor.github.io/blog"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    RafaelMalgor
# facebook_username:  StartBootstrap
linkedin_username: rafael-malgor

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-163259939-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
